//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoIntegrador.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nuevo
    {
        public int NuevosId { get; set; }
        public Nullable<int> UsuarioId { get; set; }
        public string Titulo { get; set; }
        public string DescripcionCorta { get; set; }
        public string Image { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
