//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoIntegrador.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.OrdenDetalle = new HashSet<OrdenDetalle>();
        }
    
        public int ProductoId { get; set; }
        public string ProductoName { get; set; }
        public string Image { get; set; }
        public Nullable<double> Precio { get; set; }
        public Nullable<int> UsuarioId { get; set; }
        public Nullable<int> CategoriaId { get; set; }
        public Nullable<int> ColorId { get; set; }
        public Nullable<int> ModeloId { get; set; }
        public Nullable<int> AlmacenId { get; set; }
        public Nullable<System.DateTime> VentaFechaIncial { get; set; }
        public Nullable<System.DateTime> VentaFechaFinal { get; set; }
        public Nullable<int> IsNew { get; set; }
    
        public virtual Almacen Almacen { get; set; }
        public virtual Categoria Categoria { get; set; }
        public virtual Color Color { get; set; }
        public virtual Modelo Modelo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenDetalle> OrdenDetalle { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
